### ISSUE TITLE
Support for Mozilla Firefox Addon.

### ISSUE THREAD

**Issue by sNrVJx** [adrienjoly/chrome-next-step-for-trello#70] opened 2018-06-21 14:04 UTC
Would be awesome to have this extension on Mozilla Firefox?

**Why?** Because only Mozilla Firefox supports extensions/addons on smartphones (Android/iOS). So this would work on our smartphones too this way.

**Comment by adrienjoly** [comment] 2018-06-22 09:35
(note: duplicate of #21)

I did not know that extension were usable on Firefox mobile, thanks for sharing this!

Unfortunately, I don't have enough spare time to work on this. So if you know a developer who would like to do it, please share the URL of this repository with them. (Next Step for Trello is open source, so anybody can propose contributions)

**Closed** 2019-03-03 13:17 UTC
