### ISSUE TITLE
Next step not loading on chrome, brave

### ISSUE THREAD

**Issue by arnoldskalnins** [adrienjoly/chrome-next-step-for-trello#147] opened 2023-03-01 07:35 UTC
Hi! First, I'd like to say thank you so much for the tool you have created, it helps so much. The ones that should really thank you is Trello because, like many others, I probably wouldn't even use it if it weren't for your extension. 

So like 2 days ago Next step would just stop loading. It keeps showing that the loading circle next to the name just keeps turning and nothing happens. I tried to reinstall the extension on brave - didn't help. Then installed it on fresh chrome, still no good. 

What could the problem be? I am so used to the workflow, and I have everything set up on Trello, so I really do not want to migrate.

Thank you so much
![ice_screenshot_20230301-083225](https://user-images.githubusercontent.com/126653812/222073805-5013fd18-1865-4894-9c67-7c8bb76cd1c7.png)

**Comment by CaneRaiser** [comment] 2023-03-01 15:29
I am having the same issue precisely.  I have tried unintalling and reinstalling the extension with no results.  I have also tried changing the setting on the extension but no next steps are shown.

**Comment by CuriousChipmunk** [comment] 2023-03-01 19:44
I am also experiencing the same issue.

**Comment by pillai-karthik** [comment] 2023-03-01 20:53
Same issue! Please resolve this soon 😢 @adrienjoly

**Comment by xohyun** [comment] 2023-03-02 05:05
Same issue😢😢😢

**Comment by adrienjoly** [comment] 2023-03-02 08:24
Hi all, sorry to hear about that...

Unfortunately, I don't have time to investigate these, at this time...

Could this be caused by the new limitations of Chrome Extensions? (cf #127)

Feel free to share any hints on how to fix this, or even better: a pull request that fixes the extension. I'll do my best to provide a timely review.

Best regards.

**Comment by pillai-karthik** [comment] 2023-03-02 09:51
Hi @adrienjoly 

Thank you for your reply! I completely understand your availability :(

Here's a console log -

When the Trello page loads -
![image](https://user-images.githubusercontent.com/52003038/222391966-6cbea472-a078-4595-b70d-01b6390386d3.png)
![image](https://user-images.githubusercontent.com/52003038/222392345-1d1fd5bc-75ca-40b4-9a1c-dd195ede7c6f.png)

When we click the top right button to select the display options - 
Seems like ads not loading
![image](https://user-images.githubusercontent.com/52003038/222393205-20eedf6f-26cc-489b-a6e8-14e914adb3a7.png)

I would have fixed but I don't have experience in developing extensions :(

Maybe this is because Trello changed some CSS classname or structure.

**Comment by adrienjoly** [comment] 2023-03-04 11:57
Potential fix: https://github.com/adrienjoly/chrome-next-step-for-trello/commit/1a06d26cd2096b724cd905ec72702667eee3cf44

Update of the extension in progress, it may take several minutes or hours to publish.

**Comment by pillai-karthik** [comment] 2023-03-05 10:22
Thank you @adrienjoly ! The issue is fixed now

**Comment by adrienjoly** [comment] 2023-03-05 13:03
Awesome!

Indeed, v1.21.3 is live on https://chrome.google.com/webstore/detail/next-step-for-trello/iajhmklhilkjgabejjemfbhmclgnmamf 🎉

Thank you all of your help and patience! 🙌

**Closed by adrienjoly** 2023-03-05 13:03 UTC

**Comment by bmcguire** [comment] 2023-03-06 17:03
Thanks Adrienjoly for the fix!!
