### ISSUE TITLE
Convert list item card link into a card name

### ISSUE THREAD

**Issue by MyMarvel** [adrienjoly/chrome-next-step-for-trello#128] opened 2022-01-31 04:04 UTC
Trello has a core functionality to convert a checklist item into a card. In this case the list item becomes visible as a special link with a card name, you can see it on my screenshot (sorry it's on Russian language but you'll get the point)
![image](https://user-images.githubusercontent.com/3839421/151737205-bea4abc0-022e-4bd8-a740-f0b9eca7b6ac.png)
However, when I enabled this extention, it does not convert the card link list item into a card name and looks terrible:
![image](https://user-images.githubusercontent.com/3839421/151737289-1226d4a1-418b-4188-95d2-903ae916ea66.png)
It would be great to support a conversion between trello links inside the list item into at least a card name, or even better - into a link with a card name in it.

**Comment by adrienjoly** [comment] 2022-01-31 18:09
Thank you for this feature request, Nikita!

Indeed, this feature has been requested several times. (see https://github.com/adrienjoly/chrome-next-step-for-trello/issues/40)

Unfortunately, I don't have time to implement it.

If you (or a developer you may know) are interested, feel free to contribute that feature by proposing a pull request. I'll do my best to review it and provide assistance if needed.

In the mean time, for the sake of reducing the number of pending issues, I'm closing this one as a duplicate of https://github.com/adrienjoly/chrome-next-step-for-trello/issues/40.

Best regards

Adrien

**Closed** 2022-01-31 18:10 UTC
Labels: duplicate
